# Generated by Django 4.2 on 2023-04-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_pedido_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='nome',
        ),
        migrations.AddField(
            model_name='pedido',
            name='payment_intent',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_pago',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
